### ISSUE TITLE
Unicode-equivalent symbols not treated properly

### ISSUE THREAD

**Issue by kasnerz** [ufal/lindat-translation#35]
### Issue 

An input with unnormalized Unicode symbols in Czech leads to broken translation.

### How to reproduce
Translate a Czech text in which symbols with diacritics use [combining characters](https://en.wikipedia.org/wiki/Combining_character), e.g. "ě" is create by combining a lower-case symbol "e" (U+0065) with a combining caron (U+030C).

### Example
With unnormalized diacritics:
```
In (cs):
Během našich průzkumných cest jsme narazili na menší opuštěnou stodolu. V jejím okolí se nacházela rozebraná chátrající auta. Třeba hodně známá Avie A30. Když jsme vlezli do stodoly, čekalo na nás milé překvapení v podobě Tatry 805. Tatra měla hezky zachovaný interiér.

Out (en):
We came across a menší opušte a barn. In her surroundings, the car was being dismantled. Try a lot of the Avie A30. When we got into the barn, it was waiting for the nice-nice-to-have-a-nice-to-say-a-lot-in-the-form Tatra 805. Tatra měla nicely preserved́ interiér.
```
With normalized diacritics:
```
In (cs):
Během našich průzkumných cest jsme narazili na menší opuštěnou stodolu. V jejím okolí se nacházela rozebraná chátrající auta. Třeba hodně známá Avie A30. Když jsme vlezli do stodoly, čekalo nás milé překvapení v podobě Tatry 805. Tatra měla hezky zachovaný interiér.

Out (en):
During our exploratory travels, we came across a smaller abandoned barn. Around her were dismantled ramshackle cars. Like the much-known Avie A30. When we got into the barn, we had a nice surprise in the form of Tatra 805. The Tatra had a nicely preserved interior.
```
### How to solve
Using unicode normalization during preprocessing should be enough to fix this issue.

**Comment by martinpopel** [comment]
@kosarko I see you already use `unicodedata.normalize('NFC', text)` in #34, but only for the billing purposes. Can you please adapt it so that all inputs to the backend are normalized?

**Comment by kosarko** [comment]
@martinpopel Is it a safe change for all the languages (Russian and Hindi especially)? Don't you need to know how those were trained? Is it common practice to NFC normalize the data before training?

**Comment by martinpopel** [comment]
Most of the training data is already NFC-normalized. It is a chicken-or-egg problem: if NFC-normalization is guaranteed at lindat.cz, model authors will NFC-normalize also all the training data for the future models.
I am not sure about Russian (@varisd?) and Hindi, but I strongly suggest to turn on this pre-processing for all languages at lindat.cz and if problems arise, re-train the models on NFC-normalized data.

A side note: there may be a temptation to do also NF**K**C normalization (so that e.g. … [U+2026] becomes ... [three dots]), but I don't suggest to do this because e.g. `normalize('NFKC', '1½') == '11⁄2'`.

**Comment by foxik** [comment]
Personally I think running NFC normalization is the way to go, both on the training data and service inputs. The only thing why we do not run it explicitly on training data is that we expect that it is already in NFC; and maybe we forget to run it on service inputs. 

But it is a no-brainer -- NFC is well defined and it does not lose any information.

**Comment by martinpopel** [comment]
I fully agree with @foxik.
There may be languages where optimal subwords are based on NFD (e.g. in Tamil, I think, a single Unicode character (and a single code-point in NFC, but multiple in NFD) may contain a vowel and a consonant from different syllables because the orthography is not aligned with morphology, and optimal subword split may need to separate the two syllables), but this is not the case of Czech, English, French, Russian nor German. However, even is such case, the backend toolkit should accept NFC and do the NFD-based subword tokenization internally and transparently.

BTW: this issue is in the lindat-translation repo, but it seems relevant to other Lindat services as well.

**Comment by varisd** [comment]
> Most of the training data is already NFC-normalized. It is a chicken-or-egg problem: if NFC-normalization is guaranteed at lindat.cz, model authors will NFC-normalize also all the training data for the future models.
> I am not sure about Russian (@varisd?) and Hindi, but I strongly suggest to turn on this pre-processing for all languages at lindat.cz and if problems arise, re-train the models on NFC-normalized data.
> 
> A side note: there may be a temptation to do also NF**K**C normalization (so that e.g. … [U+2026] becomes ... [three dots]), but I don't suggest to do this because e.g. `normalize('NFKC', '1½') == '11⁄2'`.

Honestly, I did not think about any kind of normalisation when I trained the models for Russian (and I have no idea about Hindi since that model was prepared by another colleague of ours).
If you can give me some quick crash course on the normalisation standards I can later check what is used in these models a if necessary retrain them (this may also include German).

**Comment by kosarko** [comment]
@varisd It's very briefly summarized in python's unicodedata.normalize (https://docs.python.org/3/library/unicodedata.html#unicodedata.normalize)
